### ISSUE TITLE
Сделать ссылки в сайдбаре кликабельными (роутинг)

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#221]
Ссылки в сайдбаре по клику должны вести на отдельные страницы. Соответственно, должен меняться адрес через History API (без /!#/).

Выбранный пункт в сайдбаре должен иметь фон, соответствующий цвету фона рабочей области. В данном случае белый.

![6 4](https://user-images.githubusercontent.com/332151/51380707-24bb1300-1b34-11e9-90bb-8c916d0008ce.png)

С открытым листом, фон выбранного пункта в сайдбаре становится светло серым.

![6 4](https://user-images.githubusercontent.com/332151/51380798-56cc7500-1b34-11e9-931f-e5b09a0df262.png)

**Comment by pepelyaeva** [comment]
Роутинг без решеточки вынесла в отдельную задачу #279.
