### ISSUE TITLE
Сверстать тулбар в листе

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#222]
Тулбар занимает всю ширину листа. Все остальные элементы листа идут ниже тулбара, потому что кнопок в нем может быть много. Пока достаточно кнопки с крестиком, которая анимировано скрывает тулбар. Фон можно сделать, например, rgba(0,0,0,.25), при наведении rgba(0,0,0,.35), при клике rgba(0,0,0,.5).

![6 4](https://user-images.githubusercontent.com/332151/51381049-eb36d780-1b34-11e9-89ef-6421d925a055.png)

Иконки в кнопках векторные. Ссылка на крестик:

https://iconmonstr.com/x-mark-1-svg/

В тулбаре будут кнопки трех видов: круглые с иконкой, очень мягкий прямоугольник с текстом или очень мягкий прямоугольник с иконками, разделенный.

![17 7](https://user-images.githubusercontent.com/332151/51381300-9cd60880-1b35-11e9-8b18-1a8c56d0c5fd.png)

**Comment by pepelyaeva** [comment]
Добавлены кнопки нужного цвета со скруглением (ветка flexberry-designer-new-style), необходимо доработать в соответствие с макетом.  Кнопки третьего вида (очень мягкий прямоугольник с иконками, разделенный) это группа кнопок ui buttons, так же необходимо привести к нужному виду. Вид настраивается при помощи переменных, при этом нужно учитывать, что есть кнопки другого вида (.basic например).

**Comment by pepelyaeva** [comment]
Замечания к pr #264.

- Убрать полужирный шрифт, В макете normal.
- Для группы кнопок отступ установлен только для первой, нужно учитывать, что в группе может быть и большее число кнопок.
- Для каждой кнопки и для группы необходимо прописывать small, нужно настроить размеры кнопок без его использования.
- Кнопки с иконкой должны быть круглой формы
![image](https://user-images.githubusercontent.com/15091209/52715835-42f32200-2fbf-11e9-83de-0f286ae9f624.png)

**Comment by pepelyaeva** [comment]
Сейчас иконки выглядят большими, предлагаю для уменьшения кнопки уменьшать не паддинги, а размер текста. Паддинги изначально указаны в em, поэтому их размер тоже уменьшится, так как зависит от размера текста. Если требуется также изменить и паддинги, то следует использовать единицы измерения em. 
[Подробнее о единицах измерения css](https://learn.javascript.ru/css-units)
