### ISSUE TITLE
Сверстать компонент «Список»

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#223]
Список это такой блок, состоящий из групп. Группы разделяются светло-серыми 1px линиями. Внутри группы строки. Строка это такой флексбокс, состоящий из двух столбцов: первый фиксированной ширины, второй: { flex-grow: 1; }. Группа строк может содержать один заголовок (например, Перечисление) или иметь заголовок в каждой строке (например, сущность, редактор, список). Во втором столбце каждой строки может быть иконка слева от текста. Если в строке кнопка, то ее часть с иконкой, должна быть висячей.

![5](https://user-images.githubusercontent.com/332151/51382409-985f1f00-1b38-11e9-9bf3-b4b389239bc5.png)

Этот же компонент может быть использован для таблиц с формами.

![6 2](https://user-images.githubusercontent.com/332151/51382500-c2b0dc80-1b38-11e9-8206-df0f60e7a166.png)

**Comment by pepelyaeva** [comment]
Не удачное расположение элементов, нужно переместить.
