### ISSUE TITLE
Сверстать компонент «Кнопка»

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#224]
Вот это кнопка.

<img width="729" alt="screenshot 2019-01-18 at 15 55 19" src="https://user-images.githubusercontent.com/332151/51382777-8467ed00-1b39-11e9-8dfb-072b7a57a6bc.png">

У нее полностью закругленные углы, возможно есть векторная иконка и текст. Предположительно, это флексбокс с выровненными по вертикали элементами. Серый цвет может поменяться на любой другой.

Иконку с плюсом можно взять отсюда:

https://iconmonstr.com/plus-thin-svg/

Пример использования кнопки в естественной среде обитания:

![5](https://user-images.githubusercontent.com/332151/51382997-09eb9d00-1b3a-11e9-90e2-8e21ed441fab.png)

**Comment by heledishel** [comment]
Нужна информация про вид кнопки при ховере. Какого цвета рамка и текст? Есть ли заливка фона каким-нибудь цветом?

**Comment by pepelyaeva** [comment]
Дополнения от Дениса из скайпа про состояния: 

> Становятся на 10% темнее при ховере и еще на 10% темнее при нажатии. Бордер, иконка и текст.
> Normal: rgba(0,0,0,X), hover: rgba(0,0,0,X+0.1), active: rgba(0,0,0,X+0.2).


Сейчас все хорошо, только текст становится rgba(0, 0, 0, 0.8), нужно, чтобы он был цвета бордера.
