### ISSUE TITLE
Сверстать блок c копирайтом

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#227]
### Цель
Сверстать блок с копирайтом и добавить его футером к страницам.

### Функциональные требования

Текст: Copyright © New platform Ltd. 2018 Создано при поддержке Фонда содействия развитию малых форм предприятий в научно-технической сфере (программа СТАРТ-2013).

### Полезные ссылки, скриншоты

<img width="1440" alt="screenshot 2019-01-21 at 09 16 34" src="https://user-images.githubusercontent.com/332151/51452734-975b0700-1d5d-11e9-9baa-d91062a3115d.png">

**Comment by pepelyaeva** [comment]
Иконки соц. сетей должны быть в svg, можно взять из [документации](https://github.com/Flexberry/flexberry.github.io/tree/master/_includes/icons). Нужно каждую иконку оформить отдельным шаблоном и встраивать инлайново в футер.
