### ISSUE TITLE
Сверстать страницу с проектами, список проектов.

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#228]
### Цель

Сверстать страницу со списком проектов. Когда у пользователя уже создан один или более проектов, они отображаются плиткой.

### Функциональные требования

- Заголовок;
- Инпут с поиском, кнопка создания нового проекта;
- Блок проекта содержит: название, описание, дату обновления и кнопку, которая прикрепляет проект в верх списка.

Ширина блока фиксирована.

Проекты упорядочены по убыванию даты обновления. Прикрепленные проекты упорядочены в алфавитном порядке по возрастанию (А-Я).

Иконка с кнопкой:

https://iconmonstr.com/pin-23-svg/

### Полезные ссылки, скриншоты

![3](https://user-images.githubusercontent.com/332151/51452952-af7f5600-1d5e-11e9-8630-c5099ae3ed78.png)

**Comment by pepelyaeva** [comment]
Иконки добавлены в рамках задачи #243
