### ISSUE TITLE
Сверстать компонент «Таблица»

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#229]
### Цель
Сверстать компонент, который представляет каждый дочерний элемент в виде строки таблицы.

### Полезные ссылки, скриншоты

![7](https://user-images.githubusercontent.com/332151/51464556-b078ad80-1d87-11e9-9c2d-40758792757e.png)

**Comment by pepelyaeva** [comment]
Таблица должна растягиваться по ширине рабочей области.

**Comment by pepelyaeva** [comment]
Дополнения от Дениса из скайпа:

> Серый текст — это плейсхолдеры. При клике на элемент они пропадают и остается каретка.

> 1 — это плейсхолдеры инпутом (см. выше). 2 — да, заголовок в таблице и плейсхолдер одинакового цвета. С одной стороны, это плохо, с другой очень бы не хотелось выделять заголовок :-(
 его читают один раз, потом он должен сливаться с фоном.

**Comment by pepelyaeva** [comment]
1. Если развернуть панель, то столбец с именем атрибута съезжает.
![image](https://user-images.githubusercontent.com/15091209/54738016-3ec8ae80-4bd4-11e9-8ace-8280852ce620.png)
2. Класс fd-table добавлен для каждой ячейки и при этом ни какие стили не привязаны к нему. Чтобы обозначить компонент, лучше использовать класс с таким названием для таблицы в целом.
3. ui checkbox в разметке нужно заменить на flexberry-checkbox
