### ISSUE TITLE
Сверстать компонент «Чекбокс»

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#230]
### Цель

Сверстать компонент «Чекбокс».

### Полезные ссылки, скриншоты

https://iconmonstr.com/checkbox-11-svg/
https://iconmonstr.com/checkbox-9-svg/

<img width="943" alt="screenshot 2019-01-21 at 14 25 11" src="https://user-images.githubusercontent.com/332151/51464974-a0150280-1d88-11e9-8f21-349093114093.png">

<img width="923" alt="screenshot 2019-01-21 at 14 25 28" src="https://user-images.githubusercontent.com/332151/51464979-a2775c80-1d88-11e9-9317-853dea762bc6.png">

**Comment by pepelyaeva** [comment]
Настроить вид компонента flexberry-checkbox.

**Comment by pepelyaeva** [comment]
Иконки добавлены в рамках задачи #243
