### ISSUE TITLE
Сверстать компонент «Круглая кнопка»

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#231]
### Цель

Сверстать компонент, который отображает иконку в круге и текст под ним.

### Функциональные требования

- Кнопка бывает в двух вариантах: цветом выделения и серым.

### Полезные ссылки, скриншоты

Отменить и создать проект:

![2](https://user-images.githubusercontent.com/332151/51465380-a2c42780-1d89-11e9-8e8f-241faa75215f.png)

Сохранить настройки:

![21](https://user-images.githubusercontent.com/332151/51465431-b7a0bb00-1d89-11e9-9773-bf3d000085ad.png)

**Comment by pepelyaeva** [comment]
Иконки добавлены в рамках задачи #243 .
Комментарии к реализации: должна быть настроена максимальная ширина для нижней надписи или для блока в целом, а не перенос текста.
