### ISSUE TITLE
Сверстать страницу генерации приложения

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#232]
### Цель

Сверстать страницу генерации приложения.

### Функциональные требования

Страница состоит из таблицы и кнопки Сохранить настроки. Ширина таблицы равна 50% от ширины страницы.

### Полезные ссылки, скриншоты

![21](https://user-images.githubusercontent.com/332151/51465709-4b728700-1d8a-11e9-88b9-9f0ef6717f69.png)

**Comment by pepelyaeva** [comment]
+ Страница Добавить проект
