### ISSUE TITLE
Адаптировать компонент "Сайдбар" для мобильной версии

### ISSUE THREAD

**Issue by fadeev** [Flexberry/ember-flexberry-designer#236]
### Цель

Адаптировать компонент "Сайдбар" для мобильной версии.

### Функциональные требования

В десктопной версии меню проекта (верхнее) и меню приложения (нижнее) разделены пустым пространством. В мобильной версии это один прокручиваемый список.

<img width="200px" src="https://user-images.githubusercontent.com/332151/51817637-5a5abb80-22ed-11e9-953a-a06d18ac43e3.png"/>

**Comment by pepelyaeva** [comment]
Также необходимо организовать общую структуру приложения. Сайдбар должен скрываться полностью, остается только кнопка, Раскрывается на весь экран.
![image](https://user-images.githubusercontent.com/15091209/56339714-c7813d00-61c8-11e9-925e-f7c1bf081dda.png)
Также необходимо настроить футер.
