### ISSUE TITLE
Реализовать панель настройки свойств класса объекта данных в UML-редакторе

### ISSUE THREAD

**Issue by s-andrey** [Flexberry/ember-flexberry-designer#238]
### Цель
Реализовать функциональную часть панели настройки свойств обычного класса объекта данных в UML-редакторе

### Функциональные требования
1. Реализовать панель (возможно лучше сделать логику отдельным компонентом) для настройки свойств класса.
2. Добавить механизм для заполнения данными свойств созданного компонента при выборе, класса на диаграмме.
3. Реализовать сохранение свойств класса.

### Требования к реализации
Свойства настройки класса должны быть аналогичны свойствам класса из win версии дизайнера. (см скриншот №1)

Стиль оформления панели должен соответствовать макету дизайна (см скриншот №2) Рекомендуется вынести на форму только основные свойства(Name, Caption, Description, storage,BSClass + еще какие-нибудь), остальные скрыть в группу "дополнительные"

### Исходный код
[hbs](https://github.com/Flexberry/ember-flexberry-designer/blob/develop/app/templates/fd-diagram-edit-form.hbs#L104) - где находится панель на которую надо добавить настройку свойств класса.

**Проект на GitHub:** https://github.com/Flexberry/ember-flexberry-designer
**Ветка:** наследоваться от последней версии ветки develop

### Документация
 - [jointjs](https://resources.jointjs.com/docs/jointjs/v2.2/joint.html) - библиотека с помощью которой реализованы объекты диаграмм.

### Аналоги, примеры реализации
Многие из панелей для настроек уже реализованы их можно посмотреть в качестве примера.
- Макет дизайна (см скриншот №2)
 - [Структура приложения](https://flexberry.github.io/ember-flexberry-designer/dummy/develop/#/fd-appstruct-form)
- Конструкторы E и L форм - в Структуре приложения выбрать в левом дереве форму и нажать редактирование.

### Полезные ссылки, скриншоты
 -  Скриншот 1 
  ![Скриншот 1](https://user-images.githubusercontent.com/18547316/51965511-988de180-248b-11e9-97ab-6f2f188a88b2.png)

 -  Скриншот 2 
  ![Скриншот 2](https://user-images.githubusercontent.com/18547316/51971837-f0344900-249b-11e9-844e-7cdcd78bace9.png)

**Comment by fadeev** [comment]
![17 3](https://user-images.githubusercontent.com/332151/51972604-96348300-249d-11e9-8d71-0d45edce8da8.png)
