### ISSUE TITLE
Добавить шрифтовые иконки

### ISSUE THREAD

**Issue by pepelyaeva** [Flexberry/ember-flexberry-designer#243]
### Цель
Сформировать из svg иконок, которые используются в макетах, шрифт и подключить к проекту.

### Функциональные требования
1. Подключить шрифты и добавить необходимые для их использования стили
2. Проверить что иконки отображаются в проекте
3. Проверить, что новые иконки не перетирают существующие

### Требования к реализации
Шрифты нужно импортировать через app.import() в ember-cli-build.js

### Исходный код
**Проект на GitHub:** https://github.com/Flexberry/ember-flexberry-designer
**Ветка:** наследоваться от flexberry-designer-new-style

### Документация
 - [semantic ui icons](https://semantic-ui.com/elements/icon.html) - используются эти иконки

**Comment by fadeev** [comment]
https://iconmonstr.com/plus-thin-svg/
https://iconmonstr.com/lock-3-svg/
https://iconmonstr.com/globe-5-svg/
https://iconmonstr.com/x-mark-thin-svg/
https://iconmonstr.com/cloud-upload-thin-svg/
https://iconmonstr.com/pin-23-svg/
https://iconmonstr.com/help-1-svg/
https://iconmonstr.com/menu-2-svg/
https://iconmonstr.com/sitemap-5-svg/
https://iconmonstr.com/sitemap-17-svg/
https://iconmonstr.com/shipping-box-6-svg/
https://iconmonstr.com/gear-1-svg/
https://iconmonstr.com/view-6-svg/
https://iconmonstr.com/email-15-svg/
https://iconmonstr.com/book-27-svg/
https://iconmonstr.com/speech-bubble-23-svg/
https://iconmonstr.com/checkbox-9-svg/
https://iconmonstr.com/trash-can-2-svg/
https://iconmonstr.com/resize-5-svg/
https://iconmonstr.com/x-mark-1-svg/
https://iconmonstr.com/eye-10-svg/
https://iconmonstr.com/triangle-1-svg/
