### ISSUE TITLE
Реализовать форму "Навигация"

### ISSUE THREAD

**Issue by s-andrey** [Flexberry/ember-flexberry-designer#306]
### Цель
Реализовать форму "Навигация".

### Функциональные требования
1. Нужно отображать дерево навигации
2. В рамках этой задачи не нужно реализовывать возможность добавления новых страниц и папок
3. Нужно добавить возможность редактирования дерева.

### Требования к реализации
1. Необходимо доработать форму fd-navigation.
2. Реализовать компонент, который получает текущий проект и отображает дерево навигации
3. Текущий проект брать из сервиса fd-current-project-context, методом getCurrentStage()
4. Под деревом должна быть кнопка для добавления корневой вершины
5. При редактировании папки, на ее странице должны быть кнопки добавления, папки и страниц.

### Исходный код
**Проект на GitHub:** https://github.com/Flexberry/ember-flexberry-designer
**Ветка:** наследоваться от последней версии ветки develop

### Полезные ссылки, скриншоты
![image](https://user-images.githubusercontent.com/18547316/60648498-7d1f6c00-9e59-11e9-90f2-dd6b1f8721c9.png)

**Comment by s-andrey** [comment]
Вопросы по форме:
1) есть кнопка (добавить страницу) для добавления страниц по адресу, для выбрать из существующих форм должна быть такая же по дизайну строка с экшеном?
2) при выборе в списке существующих форм значения как оно должно выделятся? (сейчас этот компонент взят из модели приложения, там выделение белым цветом но тут этот вариант не работает мб и там и там выделение сделать как нибудь по другому чтобы можно было переиспользовать компонент)
3) Как должна выглядеть форма создания папок и форма редактирования значений?

**Comment by fadeev** [comment]
1. Нет, в разделе "Добавить по адресу" пользователь заполняет несколько инпутов и кликает на добавить. В разделе "Выбрать из существующих" он кликает на нужный ему объект в таблице.

**Comment by fadeev** [comment]
Мой ответ выше был из расчета, что каждая страница из существующих добавляется по-отдельности. В этом варианте в таблице существующих форм выделять строки не нужно — клик по строке добавляет элемент в навигацию и скрывает правую панель.

Насчет формы создания папки: какие параметры могут быть у папки, кроме названия? По умолчанию форма выглядит точно так же как "Добавить страницу по адресу".

(сорри, случайно закрыл issue)

**Comment by s-andrey** [comment]
У папки есть только имя.
