### ISSUE TITLE
Реализация механизма соединения link с link

### ISSUE THREAD

**Issue by s-andrey** [Flexberry/ember-flexberry-designer#319]
### Цель
Создать объект для jointjs для соединения связей со связями

### Функциональные требования
Возможность присоединять связи к другим связям через вспомогательный элемент.
Обратная совместимость в Вин дизайнером.

### Требования к реализации
Данный компонент должен быть неким коннектором, в него могут входить несколько связей в выходить только одна.
При присоединении к нему других связей их начало должно пропадать (как в вин)
Надо добавить сериалайзер который будет адекватно работать:
1) с бекенда приходит обычный json, надо найти конструкцию связь к связи вычислить и разбить на структуру с коннектором.
2) jointjs передать новую структуру с коннектором и отрисовать ее.
3) при сохранении убрать коннектором и на бекенд отправить обычную структуру данных.
(подробнее см скриншоты)

### Исходный код
**Проект на GitHub:** https://github.com/Flexberry/ember-flexberry-designer
**Ветка:** наследоваться от последней версии ветки develop

### Документация
 - [jointjs](https://resources.jointjs.com/docs/jointjs/v2.2/joint.html) - библиотека с помощью которой реализованы объекты диаграмм.

### Полезные ссылки, скриншоты

link 1 разбивается на 2 jointjs связи (и всего становится 3 связи, при сохранении 3 связи снова превращаются в 2)
![image](https://user-images.githubusercontent.com/18547316/54512456-13e11f00-4976-11e9-8b9d-34b7731cba4b.png)

**Comment by kafnevod** [comment]
https://github.com/Flexberry/ember-flexberry-designer/pull/340
