### ISSUE TITLE
Поправить сохранение диаграмм

### ISSUE THREAD

**Issue by s-andrey** [Flexberry/ember-flexberry-designer#321]
### Цель
Надо исправить ошибки появляющиеся при сохранении диаграмм

### Функциональные требования
Ошибок при сохранении диаграмм быть не должно.
После сохранения диаграмма должна открываться и в вин и в веб дизайнере.

### Требования к реализации
При сохранении диаграмм через веб дизайнер падают ошибки. Предположительно проблема в JsonConverters на бекенде. При считывании repositoryObject.

### Исходный код

**Проект на GitHub:** https://github.com/Flexberry/ember-flexberry-designer
**Ветка:** наследоваться от последней версии ветки develop

**Comment by KollegOFF** [comment]
Проблема там, но пока не понятно, как ее решать, оставил комментарии в ошибке [#181287](//tfs/Common/CASEBERRY/_workitems/edit/181287).
