### ISSUE TITLE
Убрать возможность отцеплять промежуточные связи от link-коннекторов

### ISSUE THREAD

**Issue by DubrovinPavel** [Flexberry/ember-flexberry-designer#362]
### Цель
Убрать возможность отцеплять промежуточные связи от link-коннекторов, разрывая при этом основную связь

### Функциональные требования
1. Промежуточные связи должно быть невозможно отцепить от коннектора.
2. Промежуточные связи нельзя давать удалить.
3. Не основные связи можно отцеплять от коннектора.

### Требования к реализации
Нужно проверить можно ли с помощью JointJS блокировать отсоединение/удаление связей. Если нельзя, то просто скрывать через стили.

### Исходный код
**Проект на GitHub:** https://github.com/Flexberry/ember-flexberry-designer
**Ветка:** наследоваться от последней версии ветки develop

### Полезные ссылки, скриншоты
![Links4](https://user-images.githubusercontent.com/14298696/56341378-4f1d7a80-61ce-11e9-9bf9-6aeda1dd46ab.png)

**Comment by kafnevod** [comment]
К сожалению не смог разобрвться как применить 
linkTools.Remove
https://resources.jointjs.com/docs/jointjs/v2.2/joint.html#linkTools.Remove 
не ко всем связям в dai, а только к конкретным
Так что изменил для промежуточных связей markUp'ы
    toolMarkup = "&lt;g/&gt;";
    arrowheadMarkup  = "&lt;g/&gt;";
