### ISSUE TITLE
Правки дизайна

### ISSUE THREAD

**Issue by s-andrey** [Flexberry/ember-flexberry-designer#425]
### Цель
Чтобы сайт сделать красивым, правки в дизайн должна внести ты.
![image](https://user-images.githubusercontent.com/18547316/62269874-d5905c00-b44d-11e9-902b-4f95c2305ea5.png)

### Функциональные требования
1. Выделение ветвей в дереве навигации (надо чтобы выделение было белым цветом на списках + убрать подсветку при наведении)
2. Кнопки создания классов надо сделать как на макете см скрин 1
3. Аналогично пункту 2 но для диаграмм. 
4. Поправить стиль для кнопки в табличке (сделать ее круглой см скрин 2) https://github.com/Flexberry/ember-flexberry-designer/blob/develop/addon/templates/components/fd-attribute-table.hbs#L26

### Исходный код

**Проект на GitHub:** https://github.com/Flexberry/ember-flexberry-designer
**Ветка:** develop

### Полезные ссылки, скриншоты
Скрин 1
![image](https://user-images.githubusercontent.com/18547316/60967815-fd9c0c00-a334-11e9-889d-5a51991503e8.png)

Скрин 2
![image](https://user-images.githubusercontent.com/18547316/61527473-f0b6a100-aa35-11e9-8841-21ffb1fd861f.png)

**Comment by pepelyaeva** [comment]
п.4 + из за кнопки съехал заголовок, надо поправить.

**Comment by pepelyaeva** [comment]
+ Скрывать меню, если не выбран проект
